/**
 * Maps ESPN full team names to just the school/university name
 * (without the mascot). This is a complete map for the 2026 tournament field.
 */
const SCHOOL_NAME_MAP: Record<string, string> = {
  "Akron Zips": "Akron",
  "Alabama Crimson Tide": "Alabama",
  "Arizona Wildcats": "Arizona",
  "Arkansas Razorbacks": "Arkansas",
  "BYU Cougars": "BYU",
  "California Baptist Lancers": "Cal Baptist",
  "Clemson Tigers": "Clemson",
  "Duke Blue Devils": "Duke",
  "Florida Gators": "Florida",
  "Furman Paladins": "Furman",
  "Georgia Bulldogs": "Georgia",
  "Gonzaga Bulldogs": "Gonzaga",
  "Hawai'i Rainbow Warriors": "Hawai'i",
  "High Point Panthers": "High Point",
  "Hofstra Pride": "Hofstra",
  "Houston Cougars": "Houston",
  "Howard Bison": "Howard",
  "Idaho Vandals": "Idaho",
  "Illinois Fighting Illini": "Illinois",
  "Iowa Hawkeyes": "Iowa",
  "Iowa State Cyclones": "Iowa State",
  "Kansas Jayhawks": "Kansas",
  "Kennesaw State Owls": "Kennesaw State",
  "Kentucky Wildcats": "Kentucky",
  "Lehigh Mountain Hawks": "Lehigh",
  "Long Island University Sharks": "Long Island",
  "Louisville Cardinals": "Louisville",
  "McNeese Cowboys": "McNeese",
  "Miami (OH) RedHawks": "Miami (OH)",
  "Miami Hurricanes": "Miami",
  "Michigan State Spartans": "Michigan State",
  "Michigan Wolverines": "Michigan",
  "Missouri Tigers": "Missouri",
  "NC State Wolfpack": "NC State",
  "Nebraska Cornhuskers": "Nebraska",
  "North Carolina Tar Heels": "North Carolina",
  "North Dakota State Bison": "North Dakota State",
  "Northern Iowa Panthers": "Northern Iowa",
  "Ohio State Buckeyes": "Ohio State",
  "Pennsylvania Quakers": "Penn",
  "Prairie View A&M Panthers": "Prairie View A&M",
  "Purdue Boilermakers": "Purdue",
  "Queens University Royals": "Queens",
  "SMU Mustangs": "SMU",
  "Saint Louis Billikens": "Saint Louis",
  "Saint Mary's Gaels": "Saint Mary's",
  "Santa Clara Broncos": "Santa Clara",
  "Siena Saints": "Siena",
  "South Florida Bulls": "South Florida",
  "St. John's Red Storm": "St. John's",
  "TCU Horned Frogs": "TCU",
  "Tennessee State Tigers": "Tennessee State",
  "Tennessee Volunteers": "Tennessee",
  "Texas A&M Aggies": "Texas A&M",
  "Texas Longhorns": "Texas",
  "Texas Tech Red Raiders": "Texas Tech",
  "Troy Trojans": "Troy",
  "UCF Knights": "UCF",
  "UCLA Bruins": "UCLA",
  "UConn Huskies": "UConn",
  "UMBC Retrievers": "UMBC",
  "Utah State Aggies": "Utah State",
  "VCU Rams": "VCU",
  "Vanderbilt Commodores": "Vanderbilt",
  "Villanova Wildcats": "Villanova",
  "Virginia Cavaliers": "Virginia",
  "Wisconsin Badgers": "Wisconsin",
  "Wright State Raiders": "Wright State",
};

/** Get just the school name from an ESPN full team name */
export function schoolName(fullName: string): string {
  return SCHOOL_NAME_MAP[fullName] ?? fullName;
}
