CREATE TABLE `kenpom_rankings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`team_name` text NOT NULL,
	`rank` integer NOT NULL,
	`seed` integer,
	`conference` text,
	`record` text,
	`adj_em` text,
	`adj_o` text,
	`adj_o_rank` integer,
	`adj_d` text,
	`adj_d_rank` integer,
	`adj_t` text,
	`adj_t_rank` integer,
	`luck` text,
	`luck_rank` integer,
	`sos_em` text,
	`sos_em_rank` integer,
	`sos_o` text,
	`sos_o_rank` integer,
	`sos_d` text,
	`sos_d_rank` integer,
	`ncsos` text,
	`ncsos_rank` integer,
	`updated_at` text DEFAULT (datetime('now'))
);
