"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Card, CardContent } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

type TeamInfo = {
  name: string;
  abbreviation: string;
  seed: number;
  logoUrl: string | null;
};

type RoundStat = {
  round: number;
  roundName: string;
  correct: number;
  total: number;
  points: number;
  maxPossible: number;
};

type CalibrationBucket = {
  label: string;
  expectedMidpoint: number;
  actual: number;
  correct: number;
  total: number;
};

type Surprise = {
  gameId: number;
  round: number;
  roundName: string;
  confidence: number;
  pickedTeam: TeamInfo | null;
  actualWinner: TeamInfo | null;
};

type ChampionStep = {
  round: number;
  roundName: string;
  gameId: number;
  pickedTeam: TeamInfo;
  opponent: TeamInfo | null;
  confidence: number;
  isCorrect: number | null;
  gameStatus: string;
};

type SimBracketStats = {
  simUserId: number;
  name: string;
  totalPoints: number;
  rank: number;
  humansBeaten: number;
  totalParticipants: number;
  roundStats: RoundStat[];
  calibration: CalibrationBucket[];
  surprises: Surprise[];
  championPath: ChampionStep[];
  championTeam: TeamInfo | null;
};

function RobotIcon({ className = "w-6 h-6" }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} strokeLinecap="round" strokeLinejoin="round">
      <rect x="4" y="8" width="16" height="12" rx="2" />
      <path d="M12 8V4" />
      <circle cx="12" cy="3" r="1" />
      <circle cx="9" cy="14" r="1.5" fill="currentColor" />
      <circle cx="15" cy="14" r="1.5" fill="currentColor" />
      <path d="M9 18h6" />
      <path d="M2 12v4" />
      <path d="M22 12v4" />
    </svg>
  );
}

export default function SimBracketPage() {
  const router = useRouter();
  const [data, setData] = useState<SimBracketStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    async function fetchStats() {
      try {
        const res = await fetch("/api/sim-bracket/stats");
        if (!res.ok) {
          const err = await res.json();
          setError(err.error || "Failed to load sim bracket stats");
          return;
        }
        setData(await res.json());
      } catch {
        setError("Failed to load sim bracket stats");
      } finally {
        setLoading(false);
      }
    }
    fetchStats();
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[calc(100vh-4rem)]">
        <div className="flex flex-col items-center gap-4">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-[#F4793B] border-t-transparent" />
          <p className="text-sm text-muted-foreground">Loading sim bracket...</p>
        </div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="flex items-center justify-center min-h-[calc(100vh-4rem)]">
        <div className="text-center">
          <p className="text-destructive mb-2">{error || "No data available"}</p>
          <p className="text-sm text-muted-foreground">
            The sim bracket needs to be generated by an admin first.
          </p>
        </div>
      </div>
    );
  }

  const totalCorrect = data.roundStats.reduce((s, r) => s + r.correct, 0);
  const totalPicks = data.roundStats.reduce((s, r) => s + r.total, 0);

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 space-y-8">
      {/* Header */}
      <div className="flex items-center gap-4">
        <div className="w-14 h-14 rounded-2xl bg-[#1B365D]/10 flex items-center justify-center">
          <RobotIcon className="w-8 h-8 text-[#1B365D]" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-[#1B365D]">{data.name}</h1>
          <p className="text-sm text-[#5A7A99]">
            Monte Carlo simulation &mdash; 10,000 tournament runs, pick the convergent winner
          </p>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <p className="text-[10px] font-medium text-[#5A7A99] uppercase tracking-wider mb-1">
              Total Points
            </p>
            <p className="text-2xl font-bold text-[#1B365D]">{data.totalPoints}</p>
          </CardContent>
        </Card>
        <Card className="border-[#F4793B]/30">
          <CardContent className="p-4">
            <p className="text-[10px] font-medium text-[#5A7A99] uppercase tracking-wider mb-1">
              Rank
            </p>
            <p className="text-2xl font-bold text-[#F4793B]">
              #{data.rank} <span className="text-sm font-normal text-[#5A7A99]">of {data.totalParticipants}</span>
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <p className="text-[10px] font-medium text-[#5A7A99] uppercase tracking-wider mb-1">
              Correct Picks
            </p>
            <p className="text-2xl font-bold text-[#1B365D]">
              {totalCorrect}<span className="text-sm font-normal text-[#5A7A99]">/{totalPicks}</span>
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <p className="text-[10px] font-medium text-[#5A7A99] uppercase tracking-wider mb-1">
              Humans Beaten
            </p>
            <p className="text-2xl font-bold text-[#1B365D]">{data.humansBeaten}</p>
          </CardContent>
        </Card>
      </div>

      {/* View Full Bracket Link */}
      <button
        onClick={() => router.push(`/bracket/${data.simUserId}`)}
        className="text-sm text-[#F4793B] hover:underline font-medium"
      >
        View full bracket &rarr;
      </button>

      {/* Round-by-Round */}
      <section>
        <h2 className="text-lg font-semibold mb-3 text-[#1B365D]">Round-by-Round</h2>
        <Card>
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Round</TableHead>
                  <TableHead className="text-center">Correct</TableHead>
                  <TableHead className="text-right">Points</TableHead>
                  <TableHead className="text-right hidden sm:table-cell">Max</TableHead>
                  <TableHead className="text-right">Accuracy</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {data.roundStats.map((r) => (
                  <TableRow key={r.round}>
                    <TableCell className="font-medium text-[#1B365D]">{r.roundName}</TableCell>
                    <TableCell className="text-center">
                      {r.correct}/{r.total}
                    </TableCell>
                    <TableCell className="text-right font-bold">{r.points}</TableCell>
                    <TableCell className="text-right text-muted-foreground hidden sm:table-cell">
                      {r.maxPossible}
                    </TableCell>
                    <TableCell className="text-right">
                      {r.total > 0 ? (
                        <span
                          className={`font-mono text-xs ${
                            r.correct / r.total >= 0.7
                              ? "text-green-600"
                              : r.correct / r.total >= 0.5
                                ? "text-[#1B365D]"
                                : "text-red-500"
                          }`}
                        >
                          {Math.round((r.correct / r.total) * 100)}%
                        </span>
                      ) : (
                        <span className="text-[#BFD4E4]">&mdash;</span>
                      )}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </Card>
      </section>

      {/* Champion Path */}
      {data.championPath.length > 0 && (
        <section>
          <h2 className="text-lg font-semibold mb-3 text-[#1B365D]">
            Champion Path
            {data.championTeam && (
              <span className="ml-2 text-sm font-normal text-[#5A7A99]">
                ({data.championTeam.seed}) {data.championTeam.abbreviation}
              </span>
            )}
          </h2>
          <div className="flex flex-col gap-2">
            {data.championPath.map((step) => (
              <Card
                key={step.gameId}
                className={
                  step.gameStatus === "final"
                    ? step.isCorrect === 1
                      ? "border-green-200 bg-green-50/30"
                      : "border-red-200 bg-red-50/30"
                    : ""
                }
              >
                <CardContent className="p-3 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <span className="text-xs font-medium text-[#5A7A99] w-24 shrink-0">
                      {step.roundName}
                    </span>
                    <div className="flex items-center gap-1.5">
                      {step.pickedTeam.logoUrl && (
                        <img src={step.pickedTeam.logoUrl} alt="" className="w-5 h-5 object-contain" />
                      )}
                      <span className="text-sm font-bold text-[#1B365D]">
                        ({step.pickedTeam.seed}) {step.pickedTeam.abbreviation}
                      </span>
                    </div>
                    {step.opponent && (
                      <>
                        <span className="text-xs text-[#BFD4E4]">vs</span>
                        <div className="flex items-center gap-1.5">
                          {step.opponent.logoUrl && (
                            <img src={step.opponent.logoUrl} alt="" className="w-5 h-5 object-contain" />
                          )}
                          <span className="text-xs text-[#5A7A99]">
                            ({step.opponent.seed}) {step.opponent.abbreviation}
                          </span>
                        </div>
                      </>
                    )}
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-mono text-[#5A7A99]">
                      {Math.round(step.confidence * 100)}%
                    </span>
                    {step.gameStatus === "final" && (
                      <span
                        className={`text-xs font-bold ${
                          step.isCorrect === 1 ? "text-green-600" : "text-red-500"
                        }`}
                      >
                        {step.isCorrect === 1 ? "W" : "L"}
                      </span>
                    )}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      )}

      {/* Confidence Calibration */}
      {data.calibration.length > 0 && (
        <section>
          <h2 className="text-lg font-semibold mb-3 text-[#1B365D]">
            Confidence Calibration
          </h2>
          <p className="text-sm text-[#5A7A99] mb-3">
            How well the model&apos;s confidence matches actual outcomes
          </p>
          <Card>
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Confidence</TableHead>
                    <TableHead className="text-center">Games</TableHead>
                    <TableHead className="text-center">Correct</TableHead>
                    <TableHead className="text-right">Expected</TableHead>
                    <TableHead className="text-right">Actual</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data.calibration.map((b) => {
                    const diff = b.actual - b.expectedMidpoint;
                    return (
                      <TableRow key={b.label}>
                        <TableCell className="font-medium">{b.label}</TableCell>
                        <TableCell className="text-center">{b.total}</TableCell>
                        <TableCell className="text-center">{b.correct}</TableCell>
                        <TableCell className="text-right font-mono text-xs text-[#5A7A99]">
                          {Math.round(b.expectedMidpoint * 100)}%
                        </TableCell>
                        <TableCell className="text-right">
                          <span
                            className={`font-mono text-xs font-bold ${
                              diff >= 0 ? "text-green-600" : "text-red-500"
                            }`}
                          >
                            {Math.round(b.actual * 100)}%
                          </span>
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          </Card>
        </section>
      )}

      {/* Surprise Upsets */}
      {data.surprises.length > 0 && (
        <section>
          <h2 className="text-lg font-semibold mb-3 text-[#1B365D]">
            Surprise Upsets
          </h2>
          <p className="text-sm text-[#5A7A99] mb-3">
            Games where the model was confidently wrong (&gt;60%)
          </p>
          <div className="grid gap-3 sm:grid-cols-2">
            {data.surprises.map((s) => (
              <Card key={s.gameId} className="border-red-200/50">
                <CardContent className="p-4">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-medium text-[#5A7A99]">{s.roundName}</span>
                    <span className="text-xs font-mono text-red-500 font-bold">
                      {Math.round(s.confidence * 100)}% confident
                    </span>
                  </div>
                  <div className="flex items-center gap-3">
                    {s.pickedTeam && (
                      <div className="flex items-center gap-1.5 line-through opacity-60">
                        {s.pickedTeam.logoUrl && (
                          <img src={s.pickedTeam.logoUrl} alt="" className="w-5 h-5 object-contain" />
                        )}
                        <span className="text-sm text-[#1B365D]">
                          ({s.pickedTeam.seed}) {s.pickedTeam.abbreviation}
                        </span>
                      </div>
                    )}
                    <span className="text-xs text-[#BFD4E4]">&rarr;</span>
                    {s.actualWinner && (
                      <div className="flex items-center gap-1.5">
                        {s.actualWinner.logoUrl && (
                          <img src={s.actualWinner.logoUrl} alt="" className="w-5 h-5 object-contain" />
                        )}
                        <span className="text-sm font-bold text-[#1B365D]">
                          ({s.actualWinner.seed}) {s.actualWinner.abbreviation}
                        </span>
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      )}

      {/* How It Works */}
      <section>
        <details className="group">
          <summary className="flex items-center gap-2 cursor-pointer text-lg font-semibold text-[#1B365D] list-none">
            <svg
              className="w-4 h-4 text-[#5A7A99] transition-transform group-open:rotate-90"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth={2}
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M9 18l6-6-6-6" />
            </svg>
            How It Works
          </summary>
          <div className="mt-4 space-y-4">
            <Card className="border-[#F4793B]/30">
              <CardContent className="p-4 space-y-3">
                <h3 className="text-sm font-semibold text-[#1B365D]">Monte Carlo Simulation</h3>
                <p className="text-sm text-[#5A7A99] leading-relaxed">
                  The sim bracket runs <span className="text-[#1B365D] font-medium">10,000 full tournament
                  simulations</span>. In each simulation, every game&apos;s outcome is randomly sampled based
                  on the enhanced win probability. After all simulations, each game&apos;s pick is the team
                  that won that game most often. The confidence percentage is the fraction of simulations
                  that team won.
                </p>
                <p className="text-sm text-[#5A7A99] leading-relaxed">
                  This captures <span className="text-[#1B365D] font-medium">cascading path effects</span> that
                  single-pass approaches miss. A weaker team on an easier bracket path may be a better later-round
                  pick than a stronger team in a brutal region, because the Monte Carlo naturally accounts for who
                  they&apos;re likely to face.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-4 space-y-3">
                <h3 className="text-sm font-semibold text-[#1B365D]">Base Win Probability</h3>
                <p className="text-sm text-[#5A7A99] leading-relaxed">
                  Each game&apos;s win probability starts as a 70/30 blend of two signals:
                </p>
                <ul className="text-sm text-[#5A7A99] leading-relaxed space-y-1 list-disc pl-5">
                  <li>
                    <span className="text-[#1B365D] font-medium">KenPom efficiency margin (70%)</span> &mdash;
                    converts the adjEM difference between teams into a probability using a logistic function
                  </li>
                  <li>
                    <span className="text-[#1B365D] font-medium">Historical seed-matchup rates (30%)</span> &mdash;
                    e.g. 12-seeds beat 5-seeds ~36% of the time, 9-seeds beat 8-seeds ~49%
                  </li>
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-4 space-y-3">
                <h3 className="text-sm font-semibold text-[#1B365D]">Vegas Odds Blending</h3>
                <p className="text-sm text-[#5A7A99] leading-relaxed">
                  When ESPN moneyline odds are available (typically R1 games), they&apos;re blended 50/50 with
                  the base probability. Vegas lines aggregate injury info, matchup-specific factors, and sharp
                  money that pure efficiency metrics miss. Moneylines are converted to fair (vig-free)
                  probabilities before blending.
                </p>
                <div className="bg-[#0F1E33]/5 rounded px-3 py-2">
                  <code className="text-xs text-[#1B365D] font-mono">
                    enhancedProb = 0.5 &times; modelProb + 0.5 &times; vegasProb
                  </code>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-4 space-y-3">
                <h3 className="text-sm font-semibold text-[#1B365D]">Luck Regression</h3>
                <p className="text-sm text-[#5A7A99] leading-relaxed">
                  KenPom&apos;s luck metric measures how much a team&apos;s wins have exceeded what their
                  efficiency stats predict. High-luck teams have been winning close games at an unsustainable
                  rate and are more likely to regress in single-elimination play. The win probability is
                  adjusted directly:
                </p>
                <ul className="text-sm text-[#5A7A99] leading-relaxed space-y-1 list-disc pl-5">
                  <li>If a team is significantly luckier (luck diff &gt; 0.04), their win probability is reduced by 2%</li>
                  <li>If their opponent is luckier, win probability increases by 2% (opponent regresses)</li>
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-4 space-y-3">
                <h3 className="text-sm font-semibold text-[#1B365D]">Stylistic Matchup Edge</h3>
                <p className="text-sm text-[#5A7A99] leading-relaxed">
                  Not all efficiency margins are equal. A team with elite offense facing poor defense has a
                  larger edge than adjEM alone suggests. The model computes a matchup edge from KenPom&apos;s
                  adjusted offensive and defensive efficiency splits:
                </p>
                <div className="bg-[#0F1E33]/5 rounded px-3 py-2">
                  <code className="text-xs text-[#1B365D] font-mono">
                    edge = (teamB.adjO &minus; teamA.adjD) &minus; (teamA.adjO &minus; teamB.adjD)
                  </code>
                </div>
                <p className="text-sm text-[#5A7A99] leading-relaxed">
                  When the stylistic edge exceeds 4 points, the disadvantaged team&apos;s win probability
                  is reduced by up to 2%. This naturally feeds into the Monte Carlo &mdash; the team with
                  the stylistic advantage wins more simulations.
                </p>
              </CardContent>
            </Card>

            <Card className="border-[#1B365D]/20">
              <CardContent className="p-4 space-y-3">
                <h3 className="text-sm font-semibold text-[#1B365D]">Convergence</h3>
                <p className="text-sm text-[#5A7A99] leading-relaxed">
                  With 10,000 simulations, the picks converge to stable outcomes. Each simulation randomly
                  samples game results and propagates winners through the bracket, so later-round picks
                  naturally account for all possible paths &mdash; not just the most likely one. The confidence
                  percentages show how decisively the simulation converged on each pick.
                </p>
                <p className="text-sm text-[#5A7A99] leading-relaxed">
                  Lower confidence in later rounds is expected: more teams can reach those games across
                  simulations, spreading the win share. A 40% confidence in the Elite Eight means
                  that team won that specific game in 4,000 out of 10,000 tournament runs.
                </p>
              </CardContent>
            </Card>
          </div>
        </details>
      </section>
    </div>
  );
}
